name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    name: Deploy Backend
    uses: simulador-seg-spd/deploy-backend-action./.github/workflows/deploy-backend.yml@4287179a2231a0dd7255454dd5d9f89f6eed1ed3
    with:
      project-language: 'java'
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      stack-name: 'simulador-seguros-produto-backend'
