name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: produto-backend # Especifica o ambiente onde os secrets estão configurados

    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/deploy-backend.yml@main
    with:
      project-language: 'java'
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }} # Agora vai pegar o secret do ambiente
      stack-name: 'simulador-seguros-produto-backend'
