name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  deploy_backend:
    environment: produto-backend
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/deploy-backend.yml@main
    with:
      project-language: 'java'
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      stack-name: 'simulador-seguros-produto-backend'
