name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write # Necessário se você estiver usando OIDC para autenticação com AWS
  contents: read # Necessário para ler o conteúdo do repositório
  actions: write # Necessário para interagir com outras actions e workflows
jobs:
  deploy_backend:
    name: Deploy Backend
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/deploy-backend.yml@@main # Verifique se o branch está correto
    with:
      project-language: 'java'
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      stack-name: 'simulador-seguros-produto-backend'
