name: Deploy Backend

on:
  workflow_dispatch:

jobs:
  # Executa o CI para buildar a imagem e enviá-la para o ECR
  build_and_push_image:
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/ci.yml@main # Referenciando workflow de outro repositório
    with:
      project-language: ${{ inputs.project-language }}
      AWS_ECR_REPOSITORY: ${{ inputs.aws-ecr-repository }}
      AWS_REGION: ${{ inputs.aws-region }}
      AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}

  # Executa o CD para fazer o deploy no ECS
  deploy_to_ecs:
    needs: build_and_push_image
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/cd.yml@main # Referenciando workflow de outro repositório
    with:
      stack-name: ${{ inputs.stack-name }}
      AWS_ECR_REPOSITORY: ${{ inputs.aws-ecr-repository }}
      AWS_REGION: ${{ inputs.aws-region }}
      AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
      ImageUrl: ${{ needs.build_and_push_image.outputs.image-url }}
