name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    name: Deploy Backend
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/deploy-backend.yml@v1
    with:
      project-language: 'java' # Ou 'python', dependendo do projeto
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      stack-name: 'simulador-seguros-produto-backend'
