name: CI/CD produto-backend

on:
  workflow_dispatch:
  push:
    branches:
      - main # O deploy será acionado quando houver push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest
  deploy_backend:
    runs-on: ubuntu-latest
    uses: simulador-seg-spd/deploy-backend-action/.github/workflows/deploy-backend.yml@main
    with:
      project-language: 'java' # Ou 'python', dependendo do projeto
      aws-ecr-repository: 'produto/simulador-seguros-produto-backend'
      aws-region: 'sa-east-1'
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      stack-name: 'simulador-seguros-produto-backend'
